version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    branches:
      only:
        - main
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM dependencies
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-
      - run:
          name: Install NPM dependencies
          command: npm ci
      - save_cache:
          name: Save NPM dependencies
          paths:
            - ./node_modules/
          key: npm-{{ checksum "package.json" }}
      - run:
          name: Release
          command: npx semantic-release
